// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/neo-aesthetician/DashboardAesthetician.tsx": () => import("../components/mockups/neo-aesthetician/DashboardAesthetician.tsx"),
  "./components/mockups/neo-aesthetician/LandingAesthetician.tsx": () => import("../components/mockups/neo-aesthetician/LandingAesthetician.tsx"),
  "./components/mockups/neo-chef/DashboardChef.tsx": () => import("../components/mockups/neo-chef/DashboardChef.tsx"),
  "./components/mockups/neo-chef/LandingChef.tsx": () => import("../components/mockups/neo-chef/LandingChef.tsx"),
  "./components/mockups/neo-dashboard/Dashboard.tsx": () => import("../components/mockups/neo-dashboard/Dashboard.tsx"),
  "./components/mockups/neo-barber/DashboardBarber.tsx": () => import("../components/mockups/neo-barber/DashboardBarber.tsx"),
  "./components/mockups/neo-barber/LandingBarber.tsx": () => import("../components/mockups/neo-barber/LandingBarber.tsx"),
  "./components/mockups/neo-landing/LandingPage.tsx": () => import("../components/mockups/neo-landing/LandingPage.tsx"),
  "./components/mockups/neo-realtor/DashboardRealtor.tsx": () => import("../components/mockups/neo-realtor/DashboardRealtor.tsx"),
  "./components/mockups/neo-realtor/LandingRealtor.tsx": () => import("../components/mockups/neo-realtor/LandingRealtor.tsx")
};
