// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/neo-dashboard/Dashboard.tsx": () => import("../components/mockups/neo-dashboard/Dashboard.tsx"),
  "./components/mockups/neo-landing/LandingPage.tsx": () => import("../components/mockups/neo-landing/LandingPage.tsx")
};
