// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/cal-ripken/CalRipkenLanding.tsx": () => import("../components/mockups/cal-ripken/CalRipkenLanding.tsx"),
  "./components/mockups/neo-aesthetician/DashboardAesthetician.tsx": () => import("../components/mockups/neo-aesthetician/DashboardAesthetician.tsx"),
  "./components/mockups/neo-aesthetician/LandingAesthetician.tsx": () => import("../components/mockups/neo-aesthetician/LandingAesthetician.tsx"),
  "./components/mockups/neo-affiliate/AffiliateDashboard.tsx": () => import("../components/mockups/neo-affiliate/AffiliateDashboard.tsx"),
  "./components/mockups/neo-affiliate/AffiliatePage.tsx": () => import("../components/mockups/neo-affiliate/AffiliatePage.tsx"),
  "./components/mockups/neo-barber/BarberHairstylistPage.tsx": () => import("../components/mockups/neo-barber/BarberHairstylistPage.tsx"),
  "./components/mockups/neo-barber/DashboardBarber.tsx": () => import("../components/mockups/neo-barber/DashboardBarber.tsx"),
  "./components/mockups/neo-barber/LandingBarber.tsx": () => import("../components/mockups/neo-barber/LandingBarber.tsx"),
  "./components/mockups/neo-chef/DashboardChef.tsx": () => import("../components/mockups/neo-chef/DashboardChef.tsx"),
  "./components/mockups/neo-chef/LandingChef.tsx": () => import("../components/mockups/neo-chef/LandingChef.tsx"),
  "./components/mockups/neo-dashboard-copy-lGHc8gNK/NeoDashboardCopyLGHc8gNK.tsx": () => import("../components/mockups/neo-dashboard-copy-lGHc8gNK/NeoDashboardCopyLGHc8gNK.tsx"),
  "./components/mockups/neo-dashboard/Dashboard.tsx": () => import("../components/mockups/neo-dashboard/Dashboard.tsx"),
  "./components/mockups/neo-landing/LandingPage.tsx": () => import("../components/mockups/neo-landing/LandingPage.tsx"),
  "./components/mockups/neo-landing-copy-jcC_vBQK/NeoLandingCopyJcC_vBQK.tsx": () => import("../components/mockups/neo-landing-copy-jcC_vBQK/NeoLandingCopyJcC_vBQK.tsx"),
  "./components/mockups/neo-landing-v2/LandingPageFull.tsx": () => import("../components/mockups/neo-landing-v2/LandingPageFull.tsx"),
  "./components/mockups/neo-landing-v3-condensed/LandingPageV3.tsx": () => import("../components/mockups/neo-landing-v3-condensed/LandingPageV3.tsx"),
  "./components/mockups/neo-landing-v3-deepmind-glass/LandingPageV3.tsx": () => import("../components/mockups/neo-landing-v3-deepmind-glass/LandingPageV3.tsx"),
  "./components/mockups/neo-landing-v3-editorial/LandingPageV3.tsx": () => import("../components/mockups/neo-landing-v3-editorial/LandingPageV3.tsx"),
  "./components/mockups/neo-landing-v3-index/V3Index.tsx": () => import("../components/mockups/neo-landing-v3-index/V3Index.tsx"),
  "./components/mockups/neo-landing-v3-serif-mono/LandingPageV3.tsx": () => import("../components/mockups/neo-landing-v3-serif-mono/LandingPageV3.tsx"),
  "./components/mockups/neo-realtor/DashboardRealtor.tsx": () => import("../components/mockups/neo-realtor/DashboardRealtor.tsx"),
  "./components/mockups/neo-realtor/LandingRealtor.tsx": () => import("../components/mockups/neo-realtor/LandingRealtor.tsx")
};
